ckanext/fedorkg/controller.py
import logging
from urllib.parse import unquote
from uuid import uuid4

import ckan.lib.helpers as h
import ckan.logic as logic
from DeTrusty.Decomposer import Decomposer
from DeTrusty.Molecule.MTCreation import Endpoint, _accessible_endpoints
from ckan.common import request, config
from ckan.plugins import toolkit
from ckanext.fedorkg.helpers import require_access
from ckanext.fedorkg.metadata import SEMSD_PATH, MetadataConfig
from ckanext.fedorkg.model.crud import NewsQuery

DEFAULT_QUERY_KEY = 'ckanext.fedorkg.query'
DEFAULT_QUERY_NAME_KEY = 'ckanext.fedorkg.query.name'
QUERY_TIMEOUT = 'ckanext.fedorkg.timeout'

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())


class FedORKGController:

    @staticmethod
    @require_access('fedorkg_admin')
    def delete_kg(kg):
        kg = unquote(kg)
        toolkit.enqueue_job(delete_kg_from_federation, [kg], title=f'Deleting {kg} from federation')
        toolkit.h.flash_notice(toolkit._('Your request has been added to the job queue. Check the FedORKG news feed for updates on the task.'))
        return h.helper_functions.redirect_to(h.url_for('fedorkg_admin.admin'))

    @staticmethod
    @require_access('fedorkg_admin')
    def add_kg():
        kg = request.form.get('kg')
        toolkit.enqueue_job(add_kg_to_federation, [kg], title=f'Adding {kg} to federation')
        toolkit.h.flash_notice(toolkit._('Your request has been added to the job queue. Check the FedORKG news feed for updates on the task.'))
        return h.helper_functions.redirect_to(h.url_for('fedorkg_admin.admin'))

    @staticmethod
    @require_access('fedorkg_admin')
    def admin():
        error = False
        if request.method == 'POST':
            action = request.form.get('action', None)
            if action == 'default_query':
                query = request.form.get(DEFAULT_QUERY_KEY, '').strip().replace('\r\n', '\n')
                query_name = request.form.get(DEFAULT_QUERY_NAME_KEY, '').strip()
                if query != '' and query_name != '':
                    decomposed_query = None
                    try:
                        decomposed_query = Decomposer(query, MetadataConfig()).decompose()
                    except:
                        error = True
                        toolkit.h.flash_error(toolkit._('The query is malformed. Please, check your syntax.'))

                    if not error:
                        if decomposed_query is None:
                            toolkit.h.flash_error(toolkit._('The query cannot be answer by the federation of FedORKG.'))
                        else:
                            logic.get_action(u'config_option_update')({
                                u'user': toolkit.c.user
                            }, {
                                DEFAULT_QUERY_KEY: query.replace('\n', '\\n'),
                                DEFAULT_QUERY_NAME_KEY: query_name
                            })
                            toolkit.h.flash_success(toolkit._('The default query has been updated successfully.'))
                else:
                    toolkit.h.flash_error(toolkit._('The default query and its name are required.'))
            elif action == 'query_timeout':
                timeout = request.form.get(QUERY_TIMEOUT, '')
                try:
                    timeout = int(timeout)
                except ValueError:
                    error = True
                    toolkit.h.flash_error(toolkit._('The query timeout is specified in full seconds. Please, provide input that can be parsed as an integer.'))

                if not error:
                    logic.get_action(u'config_option_update')({
                        u'user': toolkit.c.user
                    }, {
                        QUERY_TIMEOUT: timeout
                    })
                    toolkit.h.flash_success(toolkit._('New query timeout set successfully.'))
            elif action == 'delete_news':
                news_id = request.form.get('news_id', None)
                if news_id is not None:
                    NewsQuery.delete_news(news_id)

        return toolkit.render('admin_fedorkg.jinja2',
                              extra_vars={
                                  'query': config.get(DEFAULT_QUERY_KEY).strip().replace('\\n', '\n'),
                                  'query_name': config.get(DEFAULT_QUERY_NAME_KEY).strip().replace('\\n', '\n'),
                                  'timeout': config.get(QUERY_TIMEOUT),
                                  'kgs': sorted(list(MetadataConfig().getEndpoints().keys())),
                                  'fedorkg_news': NewsQuery.read_all_news()
                              })


def add_kg_to_federation(kg):
    NewsQuery.create(uuid4(), kg, 'notice', toolkit._('Starting to add the knowledge graph.'))
    error = False
    msg = toolkit._('Added the knowledge graph successfully.')
    endpoint = Endpoint(kg)
    accessible = endpoint in _accessible_endpoints([endpoint])
    if accessible:
        try:
            metadata = MetadataConfig()
            metadata.add_endpoint(kg)
            metadata.saveToFile(SEMSD_PATH)
        except Exception as e:
            error = True
            logger.exception(e)
            msg = toolkit._('Exception while adding! {exc_type} {exc_args}').format(
                exc_type=type(e).__name__,
                exc_args=e.args
            )
    else:
        error = True
        msg = toolkit._('The knowledge graph is not accessible and, hence, cannot be added to the federation.')

    NewsQuery.create(uuid4(), kg, 'error' if error else 'success', msg)


def delete_kg_from_federation(kg):
    NewsQuery.create(uuid4(), kg, 'notice', toolkit._('Starting to delete the knowledge graph.'))
    error = False
    msg = toolkit._('Removed the knowledge graph successfully.')
    try:
        metadata = MetadataConfig()
        metadata.delete_endpoint(kg)
        metadata.saveToFile(SEMSD_PATH)
    except Exception as e:
        error = True
        logger.exception(e)
        msg = toolkit._('Exception while removing! {exc_type} {exc_args}').format(
            exc_type=type(e).__name__,
            exc_args=e.args
        )

    NewsQuery.create(uuid4(), kg, 'error' if error else 'success', msg)

ckanext/fedorkg/views.py
import os

import requests
from DeTrusty import __version__ as detrusty_version
from DeTrusty import run_query
from ckan.common import request, config
from ckan.plugins import toolkit
from ckanext.fedorkg import __version__ as fedorkg_version
from ckanext.fedorkg.controller import FedORKGController, DEFAULT_QUERY_KEY, DEFAULT_QUERY_NAME_KEY, QUERY_TIMEOUT
from ckanext.fedorkg.metadata import FEDORKG_PATH, MetadataConfig
from flask import Blueprint, jsonify, request

fedorkg = Blueprint('fedorkg', __name__, url_prefix='/fedorkg')
admin_bp = Blueprint('fedorkg_admin', __name__ + '_admin', url_prefix='/ckan-admin')


def init_prompt():
    with open(os.path.join(FEDORKG_PATH, 'prompt.txt'), 'r', encoding='utf-8') as prompt_file:
        return prompt_file.read()


prompt = init_prompt()


def query_editor():
    if toolkit.check_ckan_version(min_version='2.10'):
        margin = '-0.75rem'
    else:
        margin = '-15px'
    return toolkit.render('sparql.jinja2',
                          extra_vars={
                              'detrusty_version': detrusty_version,
                              'fedorkg_version': fedorkg_version,
                              'default_query': config.get(DEFAULT_QUERY_KEY, ''),
                              'default_query_name': config.get(DEFAULT_QUERY_NAME_KEY, ''),
                              'margin': margin,
                              'timeout': config.get(QUERY_TIMEOUT)
                          })


def sparql():
    query = request.values.get('query', None)
    if query is None:
        return jsonify({"result": [], "error": "No query passed."})
    yasqe = request.values.get('yasqe', False)
    return jsonify(
        run_query(
            query=query,
            config=MetadataConfig(),
            join_stars_locally=False,
            yasqe=yasqe,
            timeout=int(config.get(QUERY_TIMEOUT))
        )
    )


def llm():
    question = request.values.get('question', None)
    if question is None:
        raise ValueError('ERROR: No question passed.')
    elif len(question) > 128:
        raise ValueError('ERROR: Your question exceeds 128 characters.')
    else:
        api_key = os.environ.get('OPENAI_API_KEY', None)
        if api_key is None:
            raise ValueError('ERROR: Missing OpenAI API key.')

        headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {api_key}'
        }

        data = {
            "model": "o4-mini",
            "messages": [
                {"role": "user", "content": f"{prompt}\n{question}"}
            ]
        }

        try:
            response = requests.post('https://api.openai.com/v1/chat/completions', headers=headers, json=data)
            response.raise_for_status()  # Raise an error for bad status codes

            content = response.json()['choices'][0]['message']['content']
            return content

        except requests.exceptions.HTTPError as http_err:
            raise RuntimeError(f"HTTP error occurred: {http_err}")
        except Exception as err:
            raise RuntimeError(f"An error occurred: {err}")


fedorkg.add_url_rule('/sparql', view_func=query_editor, methods=['GET'])
fedorkg.add_url_rule('/sparql', view_func=sparql, methods=['POST'])
fedorkg.add_url_rule('/llm', view_func=llm, methods=['POST'])
admin_bp.add_url_rule('/fedorkg', view_func=FedORKGController.admin, methods=['GET', 'POST'])
admin_bp.add_url_rule('/fedorkg/delete_kg/<kg>', view_func=FedORKGController.delete_kg, methods=['POST'])
admin_bp.add_url_rule('/fedorkg/add_kg', view_func=FedORKGController.add_kg, methods=['POST'])


def get_blueprints():
    return [fedorkg, admin_bp]

ckanext/fedorkg/templates/admin.jinja2
{% extends "admin/base.html" %}

{% import 'macros/form.html' as form %}

{% block primary_content_inner %}
    {% asset 'fedorkg/admin' %}

    {% if msg %}
        <div class="ui-state {% if error %}ui-state-error{% else %}ui-state-success{% endif %}">
            {{ msg }}
        </div>
    {% endif %}
    <div id="admin_spanner" class="spanner">
        <div id="admin_loader" class="admin_loader"></div>
        <div><p>{% trans %}Processing request, please be patient.{% endtrans %}</p></div>
    </div>

    <h2>{% trans %}Default Query{% endtrans %}</h2>
    <div>
        <form method="POST" action="{{ h.url_for('fedorkg_admin.admin') }}">
            {{ form.input('ckanext.fedorkg.query.name', label=_('Default Query Name'), value=query_name, placeholder=_('default query name'), is_required=true) }}
            {{ form.textarea('ckanext.fedorkg.query', 'field-ckanext.fedorkg.query', label=_('Default Query'), value=query, is_required=true) }}
            <input type="hidden" name="action" value="default_query">
            <div class="form-actions">
                <button type="submit" class="btn btn-primary" title="{% trans %}Set default query{% endtrans %}">{% trans %}Update{% endtrans %}</button>
            </div>
        </form>
    </div>

    <h2>{% trans %}Query Execution Timeout{% endtrans %}</h2>
    <div>
        <form method="POST" action="{{ h.url_for('fedorkg_admin.admin') }}">
            {{ form.input('ckanext.fedorkg.timeout', label=_('Query Timeout (in seconds)'), value=timeout, placeholder=_('query execution timeout'), is_required=true, type='number', attrs={'class': 'form-control', 'min': 0}) }}
            <input type="hidden" name="action" value="query_timeout">
            <div class="form-actions">
                <button type="submit" class="btn btn-primary" title="{% trans %}Set query timeout{% endtrans %}">{% trans %}Update{% endtrans %}</button>
            </div>
        </form>
    </div>

    <h2>{% trans %}Knowledge Graphs in the Federation{% endtrans %}</h2>
    <table class="table table-header table-hover table-bordered">
        <thead>
            <tr>
                <th colspan="2">{% trans %}Knowledge Graph{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
            {% for kg in kgs %}
                <tr>
                    <td><a href="{{ kg }}" target="_blank">{{ kg }}</a></td>
                    <td class="center">
                        <form class="admin" method="POST" action="{{ h.url_for('fedorkg_admin.admin') }}">
                            <input type="hidden" name="kg" value="{{ kg }}">
                            <input type="hidden" name="action" value="0">
                            <button class="btn btn-danger btn-sm" title="{% trans %}Remove knowledge graph from the federation{% endtrans %}">
                                <i class="fa fa-trash"></i>
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <form class="admin" method="POST" action="{{ h.url_for('fedorkg_admin.admin') }}">
                    <input type="hidden" name="action" value="1">
                    <td>
                        <input class="form-control" type="text" name="kg" placeholder="{% trans %}URL of the SPARQL endpoint{% endtrans %}" size="60" required>
                    </td>
                    <td class="center">
                        <button class="btn btn-success btn-sm" title="{% trans %}Add knowledge graph to the federation{% endtrans %}">
                                <i class="fa fa-plus"></i>
                        </button>
                    </td>
                </form>
            </tr>
        </tbody>
    </table>
{% endblock %}

{% block secondary_content %}
    <div class="module module-narrow module-shallow">
        <h2 class="module-heading">
            <i class="fa fa-info-circle"></i>
            FedORKG
        </h2>
        <div class="module-content">
            {% trans %}
                <p>Configuration options to manage the FedORKG instance.</p>
                <p><strong>Default Query Name:</strong> The title of the tab in the SPARQL query editor holding the default query.</p>
                <p><strong>Default Query:</strong> The default query shown in the SPARQL query editor.</p>
                <p><strong>Query Timeout:</strong> The maximum time in seconds a query is executed. Unfinished queries are canceled and return no result.</p>
                <p><strong>Knowledge Graphs in the Federation:</strong> Mange the knowledge graphs that are included in the federation of FedORKG. Keep in mind that only included knowledge graphs can be queried.</p>
            {% endtrans %}
        </div>
    </div>
{% endblock %}

ckanext/fedorkg/templates/admin_fedorkg.jinja2
{% extends "admin/base.html" %}

{% import 'macros/form.html' as form %}

{% macro row_type(notification_type) %}
    {% if notification_type | lower == 'success' %}
        {{ 'row_success' }}
    {% elif notification_type | lower == 'error' %}
        {{ 'row_danger' }}
    {% else %}
        {{ 'row_notice' }}
    {% endif %}
{% endmacro %}

{% block primary_content_inner %}
    {% asset 'fedorkg/admin-css' %}

    <h2>{% trans %}Default Query{% endtrans %}</h2>
    <div>
        <form method="POST" action="{{ h.url_for('fedorkg_admin.admin') }}">
            {{ form.input('ckanext.fedorkg.query.name', label=_('Default Query Name'), value=query_name, placeholder=_('default query name'), is_required=true) }}
            {{ form.textarea('ckanext.fedorkg.query', 'field-ckanext.fedorkg.query', label=_('Default Query'), value=query, is_required=true) }}
            <input type="hidden" name="action" value="default_query">
            <div class="form-actions">
                <button type="submit" class="btn btn-primary" title="{% trans %}Set default query{% endtrans %}">{% trans %}Update{% endtrans %}</button>
            </div>
        </form>
    </div>

    <hr>
    <h2>{% trans %}Query Execution Timeout{% endtrans %}</h2>
    <div>
        <form method="POST" action="{{ h.url_for('fedorkg_admin.admin') }}">
            {{ form.input('ckanext.fedorkg.timeout', label=_('Query Timeout (in seconds)'), value=timeout, placeholder=_('query execution timeout'), is_required=true, type='number', attrs={'class': 'form-control', 'min': 0}) }}
            <input type="hidden" name="action" value="query_timeout">
            <div class="form-actions">
                <button type="submit" class="btn btn-primary" title="{% trans %}Set query timeout{% endtrans %}">{% trans %}Update{% endtrans %}</button>
            </div>
        </form>
    </div>

    <hr>
    <h2>{% trans %}Knowledge Graphs in the Federation{% endtrans %}</h2>
    <table class="table table-header table-hover table-bordered">
        <thead>
            <tr>
                <th colspan="2">{% trans %}Knowledge Graph{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
            {% for kg in kgs %}
                <tr>
                    <td><a href="{{ kg }}" target="_blank">{{ kg }}</a></td>
                    <td class="center">
                        <form class="admin" method="POST" action="" data-module="basic-form" novalidate="">
                            <a class="btn btn-danger btn-sm" title="{% trans %}Remove knowledge graph from the federation{% endtrans %}" href="{{ h.url_for('fedorkg_admin.delete_kg', **{'kg': kg | urlencode | replace('/', '%2f') }) }}" data-module="confirm-action" data-module-content="{{ _('Are you sure you want to delete this knowledge graph?') }}">
                                <i class="fa fa-trash"></i>
                            </a>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <form class="admin" method="POST" action="{{ h.url_for('fedorkg_admin.add_kg') }}">
                    <td>
                        <input class="form-control" type="text" name="kg" placeholder="{% trans %}URL of the SPARQL endpoint of the knowledge graph{% endtrans %}" size="60" required>
                    </td>
                    <td class="center">
                        <button class="btn btn-success btn-sm" title="{% trans %}Add knowledge graph to the federation{% endtrans %}">
                            <i class="fa fa-plus"></i>
                        </button>
                    </td>
                </form>
            </tr>
        </tbody>
    </table>

    <hr>
    <h2>{% trans %}FedORKG News{% endtrans %}</h2>
    <div>
        {% if fedorkg_news %}
            <table class="table table-header table-hover table-bordered" id="fedorkg_news">
                <thead>
                <tr>
                    <th>{% trans %}Knowledge Graph{% endtrans %}</th>
                    <th>{% trans %}Message{% endtrans %}</th>
                    <th>{% trans %}Date{% endtrans %}</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for news in fedorkg_news %}
                    <tr class="{{ row_type(news.notification_type) | trim }}">
                        <td>{{ news.endpoint_url }}</td>
                        <td>{{ news.message }}</td>
                        <td>{{ news.date }}</td>
                        <td class="center">
                            <form method="POST" action="{{ h.url_for('fedorkg_admin.admin') }}">
                                <input type="hidden" name="action" value="delete_news">
                                <input type="hidden" name="news_id" value="{{ news.identifier }}">
                                <button class="btn btn-danger btn-sm" title="{% trans %}Remove this news entry{% endtrans %}">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            {% trans %}There are currently no news about added or deleted knowledge graphs.{% endtrans %}
            {% trans %}If you add or delete knowledge graphs to FedORKG, the result of the background tasks will show up here.{% endtrans %}
        {% endif %}
    </div>
{% endblock %}

{% block secondary_content %}
    <div class="module module-narrow module-shallow">
        <h2 class="module-heading">
            <i class="fa fa-info-circle"></i>
            FedORKG
        </h2>
        <div class="module-content">
            <p>{% trans %}Configuration options to manage the FedORKG instance.{% endtrans %}</p>
            <p><strong>{% trans %}Default Query Name{% endtrans %}:</strong> {% trans %}The title of the tab in the SPARQL query editor holding the default query.{% endtrans %}</p>
            <p><strong>{% trans %}Default Query{% endtrans %}:</strong> {% trans %}The default query shown in the SPARQL query editor.{% endtrans %}</p>
            <p><strong>{% trans %}Query Timeout{% endtrans %}:</strong> {% trans %}The maximum time in seconds a query is executed. Unfinished queries are canceled and return no result.{% endtrans %}</p>
            <p><strong>{% trans %}Knowledge Graphs in the Federation{% endtrans %}:</strong> {% trans %}Mange the knowledge graphs that are included in the federation of FedORKG. Keep in mind that only included knowledge graphs can be queried.{% endtrans %}</p>
            <p><strong>{% trans %}FedORKG News{% endtrans %}:</strong> {% trans %}A log of the background tasks for adding and deleting knowledge graphs.{% endtrans %}</p>
        </div>
    </div>
{% endblock %}

ckanext/fedorkg/templates/header.html
{% ckan_extends %}

{% block header_site_navigation_tabs %}
    {{ super() }}
    <li {% if h.fedorkg_is_fedorkg_page() %} class="active"{% endif %}><a href="{{ h.url_for('fedorkg.query_editor') }}">FedORKG</a></li>
{% endblock %}

ckanext/fedorkg/templates/sparql.jinja2
{% extends "page.html" %}

{% block breadcrumb_content %}
    <li class="active"><a href="{{ h.url_for('fedorkg.query_editor') }}">FedORKG</a></li>
{% endblock %}

{% block secondary %}{% endblock %}

{% block primary_content %}
    <script>
        const default_query = "{{ default_query|safe }}",
              default_query_name = "{{ default_query_name }}";
    </script>
    {% asset 'fedorkg/query' %}
    <div class="mb-6 mt-6 mx-2" id="content-wrap">
        <details class="mb-3" id="details-llm" open>
            <summary class="font-bold"><i class="fa fa-flask" aria-hidden="true"></i>&nbsp;BETA: LDMAsk - {% trans %}LLM-based Question Answering{% endtrans %}</summary>
            <div class="mb-3 py-2">
                {% trans %}LDMAsk utilizes the LLM <i>o4-mini</i>. If you do not know what you could ask, here are some examples:{% endtrans %}
                <ul>
                    <li class="question">{% trans %}What are the datasets that contain the keyword "cancer" in the description of the dataset?{% endtrans %}</li>
                    <li class="question">{% trans %}What is the frequency of the datasets per data formats?{% endtrans %}</li>
                    <li class="question">{% trans %}What is the frequency of the datasets per organizations?{% endtrans %}</li>
                    <li class="question">{% trans %}What are the resources that include word "metadata" in the description of the resource?{% endtrans %}</li>
                    <li class="question">{% trans %}What are title, year, and research field label of the papers that describe a dataset?{% endtrans %}</li>
                    <li class="question">{% trans %}What is the title of the datasets that are described by papers, also provide title, year, and research field label of these papers?{% endtrans %}</li>
                </ul>

                <form id="llm" method="post">
                    <label for="question">{% trans %}Question{% endtrans %}</label>
                    <input type="text" id="question" name="question" maxlength="136" required>
                    <div style="display: contents">
                        <div id="loading"></div>
                        <input type="submit" id="llm_submit" value="{% trans %}Ask{% endtrans %}">
                    </div>
                </form>
            </div>
        </details>

        {% trans %}You can use the SPARQL query editor below to run SPARQL queries over a federation of open research knowledge graphs.{% endtrans %}
        {% trans %}Alternatively, you can try out the beta version of our LLM-based question answering above. This feature will translate your natural language question into a SPARQL query and execute it for you.{% endtrans %}
        <p id="timeout">
            <b>{% trans %}Query execution timeout:{% endtrans %}</b>
            {% trans timeout %}
                {{ timeout }} second
                {% pluralize %}
                {{ timeout }} seconds
            {% endtrans %}
        </p>
        <div class="mt-2" id="yasgui"></div>
    </div>

    <footer id="footer" style="margin-left: {{ margin }};">
        <div class="footer"><a href="https://github.com/SDM-TIB/ckanext-fedorkg" target="_blank">FedORKG</a>&nbsp;v{{ fedorkg_version }}</div>
        <div class="footer">is powered by</div>
        <div class="footer"><a href="https://github.com/SDM-TIB/DeTrusty" target="_blank"><img src="https://raw.githubusercontent.com/SDM-TIB/DeTrusty/refs/heads/master/images/icon.png" alt="Logo of DeTrusty">DeTrusty</a>&nbsp;v{{ detrusty_version }}</div>
    </footer>
{% endblock %}